#!/usr/bin/env python3
"""Filter Keyword Planner export: keep only Spain-country-level rows (no city/island/site-specific)."""

from __future__ import annotations

import csv
import re
import sys
import unicodedata
from pathlib import Path


def norm(s: str) -> str:
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    return s.lower()


# Whole-keyword phrases (substring match after norm + spaces padded)
PHRASE_EXCLUDE = [
    "costa brava",
    "costa del sol",
    "costa blanca",
    "costa dorada",
    "costa verde",
    "costa tropical",
    "costa de la luz",
    "costa azahar",
    "costa calida",
    "costa tropical",
    "camino de santiago",
    "camino frances",
    "pyrenees",
    "picos de europa",
    "sierra nevada",
    "donana",
    "dona ana",
    "tablas de daimiel",
    "teide",
    "montserrat",
    "alhambra",
    "sagrada familia",
    "park guell",
    "parc guell",
    "royal palace madrid",
    "canary islands",
    "balearic",
    "islas canarias",
    "islas baleares",
    "san sebastian",
    "san sebastian",
    "donostia",
    "la palma",
    "la gomera",
    "el hierro",
    "gran canaria",
    "fuerteventura",
    "lanzarote",
    "tenerife",
    "ibiza",
    "mallorca",
    "majorca",
    "menorca",
    "formentera",
    "palma de mallorca",
    "las palmas",
    "ciudad real",
    "puerto rico",
    "basque country",
    "pais vasco",
    "país vasco",
    "euskadi",
]

# Single tokens that imply a specific place (word-boundary match)
TOKEN_EXCLUDE = {
    # Cities & large towns (tourism-heavy)
    "barcelona",
    "madrid",
    "seville",
    "sevilla",
    "granada",
    "valencia",
    "malaga",
    "málaga",
    "bilbao",
    "cordoba",
    "córdoba",
    "toledo",
    "marbella",
    "zaragoza",
    "murcia",
    "alicante",
    "cadiz",
    "cádiz",
    "salamanca",
    "burgos",
    "oviedo",
    "santander",
    "pamplona",
    "leon",
    "león",
    "vigo",
    "gijon",
    "gijón",
    "badajoz",
    "cartagena",
    "palma",
    "palmas",
    "torremolinos",
    "benidorm",
    "lloret",
    "sitges",
    "tarifa",
    "ronda",
    "nerja",
    "estepona",
    "fuengirola",
    "denia",
    "dénia",
    "javea",
    "xabia",
    "calpe",
    "altea",
    "torrevieja",
    "tarragona",
    "girona",
    "gerona",
    "figueres",
    "roses",
    "cadaques",
    "lleida",
    "lerida",
    "reus",
    "castellon",
    "castellón",
    "merida",
    "mérida",
    "segovia",
    "avila",
    "ávila",
    "cuenca",
    "jaen",
    "jaén",
    "huelva",
    "almeria",
    "almería",
    "lorca",
    "elche",
    "alcoy",
    "soria",
    "teruel",
    "huesca",
    "logrono",
    "logroño",
    "vitoria",
    "gasteiz",
    "burgos",
    "palencia",
    "valladolid",
    "leon",
    "ourense",
    "orense",
    "pontevedra",
    "lugo",
    "a coruna",
    "coruna",
    "la coruna",
    "compostela",
    "santiago",
    "benalmadena",
    "benalmádena",
    "mijas",
    "estepona",
    "roquetas",
    "aguadulce",
    "salou",
    "cambrils",
    "sitges",
    "castelldefels",
    "mataro",
    "badalona",
    "cornella",
    " Hospitalet",
    "terrassa",
    "sabadell",
    "manresa",
    "vic",
    "blanes",
    "tossa",
    "lloret",
    "calella",
    "malgrat",
    "vilanova",
    "sitges",
    "mahon",
    "mahón",
    "ciutadella",
    "soller",
    "sóller",
    "pollensa",
    "pollença",
    "alcudia",
    "alcúdia",
    "magaluf",
    "palmanova",
    "puerto banus",
    "banús",
    "estepona",
    "jerez",
    "chipiona",
    "vejer",
    "conil",
    "chiclana",
    "cadiz",
    "tarifa",
    "velez",
    "motril",
    "antequera",
    "ubeda",
    "úbeda",
    "baeza",
    "linares",
    "jaen",
    "guadix",
    "velez",
    "almuñecar",
    "salobreña",
    "torrox",
    "frigiliana",
    "competa",
    "velez",
    "cartagena",
    "lorca",
    "aguilas",
    "lorca",
    "murcia",
    "caravaca",
    "yecla",
    "jumilla",
    "alcoy",
    "benidorm",
    "denia",
    "calpe",
    "xativa",
    "gandia",
    "requena",
    "almansa",
    "albacete",
    "cuenca",
    "guadalajara",
    "mostoles",
    "alcorcon",
    "getafe",
    "leganes",
    "alcala",
    "aranjuez",
    "segovia",
    "avila",
    "salamanca",
    "plasencia",
    "caceres",
    "cáceres",
    "merida",
    "badajoz",
    "zafra",
    "trujillo",
    "caceres",
    "toledo",
    "aranjuez",
    "segovia",
    "cuenca",
    "guadalajara",
    "siguenza",
    "sigüenza",
    "albarracin",
    "teruel",
    "cuenca",
    "zaragoza",
    "huesca",
    "jaca",
    "ainsa",
    "formigal",
    "benasque",
    "cerler",
    "panticosa",
    "canfranc",
    "ordesa",
    "ainhoa",
    " Hondarribia",
    "getxo",
    "portugalete",
    "guernica",
    "gernika",
    "zarautz",
    "zarauz",
    "lekeitio",
    "bilbao",
    "vitoria",
    "logrono",
    "laguardia",
    "haro",
    "santo domingo",
    "burgos",
    "miranda",
    "palencia",
    "leon",
    "ponferrada",
    "astorga",
    "villafranca",
    "salamanca",
    "avila",
    "segovia",
    "arevalo",
    "medina",
    "aranjuez",
    "aranjuez",
    "chinchon",
    "chinchón",
    "el escorial",
    "escorial",
    "aranjuez",
    "aranjuez",
    "segovia",
    "aranjuez",
    "cuenca",
    "consuegra",
    "tomelloso",
    "valdepenas",
    "ciudad real",
    "puertollano",
    "almaden",
    "don quijote",
    "campo de criptana",
    "consuegra",
    "toledo",
    "talavera",
    "ojeda",
    "merida",
    "trujillo",
    "caceres",
    "plasencia",
    "hervas",
    "bejar",
    "béjar",
    "salamanca",
    "ciudad rodrigo",
    "zamora",
    "benavente",
    "leon",
    "ponferrada",
    "villafranca",
    "bierzo",
    "ponferrada",
    "ribadesella",
    "cangas",
    "covadonga",
    "gijon",
    "oviedo",
    "aviles",
    "aviles",
    "luarca",
    "ribadesella",
    "lastres",
    "colunga",
    "penarronda",
    "salinas",
    "suances",
    "santander",
    "santoña",
    "laredo",
    "castro",
    "bilbao",
    "zarautz",
    "san sebastian",
    "pamplona",
    "tudela",
    "olite",
    "roncesvalles",
    "jaca",
    "ainsa",
    "balaguer",
    "lleida",
    "montserrat",
    "sitges",
    "vilanova",
    "malgrat",
    "blanes",
    "tossa",
    "lloret",
    "empuriabrava",
    "roses",
    "cadaques",
    "begur",
    "palamos",
    "tossa",
    "calella",
    "malgrat",
    "mataro",
    "vilassar",
    "premia",
    "badalona",
    "castelldefels",
    "sitges",
    "vilanova",
    "sitges",
    "tarragona",
    "salou",
    "cambrils",
    "delta del ebro",
    "morella",
    "peniscola",
    "benicassim",
    "benicasim",
    "castellon",
    "gandia",
    "denia",
    "javea",
    "calpe",
    "altea",
    "benidorm",
    "finestrat",
    "villajoyosa",
    "alicante",
    "elche",
    "torrevieja",
    "cartagena",
    "lorca",
    "aguilas",
    "mazarron",
    "la manga",
    "mar menor",
    "murcia",
    "caravaca",
    "lorca",
    "yecla",
    "jumilla",
    "molina",
    "calasparra",
    "cehegin",
    "caravaca",
    "totana",
    "lorca",
    "aguilas",
    "veruela",
    "alcaniz",
    "teruel",
    "albarracin",
    "cuenca",
    "consuegra",
    "toledo",
    "aranjuez",
    "chinchon",
    "aranjuez",
    "segovia",
    "medina del campo",
    "avila",
    "salamanca",
    "ciudad rodrigo",
    "bejar",
    "plasencia",
    "trujillo",
    "caceres",
    "merida",
    "badajoz",
    "zafra",
    "jerez",
    "vejer",
    "tarifa",
    "conil",
    "chiclana",
    "sanlucar",
    "rocio",
    "huelva",
    "isla cristina",
    "ayamonte",
    "punta umbria",
    "almeria",
    "roquetas",
    "aguadulce",
    "almerimar",
    "mojacar",
    "carboneras",
    "nijar",
    "granada",
    "alhambra",
    "sierra nevada",
    "guadix",
    "baeza",
    "ubeda",
    "cordoba",
    "montilla",
    "priego",
    "antequera",
    "ronda",
    "marbella",
    "estepona",
    "fuengirola",
    "torremolinos",
    "benalmadena",
    "malaga",
    "nerja",
    "frigiliana",
    "almunecar",
    "salobreña",
    "motril",
    "almuñecar",
    "granada",
    "jaen",
    "baeza",
    "ubeda",
    "linares",
    "cordoba",
    "priego",
    "zuheros",
    "cabra",
    "antequera",
    "el chorro",
    "caminito del rey",
    "ronda",
    "setenil",
    " Grazalema",
    "ubrique",
    "tarifa",
    "vejer",
    "cadiz",
    "conil",
    "chipiona",
    "sanlucar",
    "jerez",
    "puerto de santa maria",
    "el puerto",
    "chiclana",
    "velez",
    "motril",
    "salobreña",
    "almunecar",
    "nerja",
    "torrox",
    "competa",
    "frigiliana",
    "fuengirola",
    "marbella",
    "estepona",
    "san pedro",
    "benalmadena",
    "torremolinos",
    "malaga",
    "antequera",
    "ronda",
    "setenil",
    " Grazalema",
    "ubrique",
    "jerez",
    "chiclana",
    "la linea",
    "algeciras",
    "tarifa",
    "gibraltar",
    "ceuta",
    "melilla",
    "tangier",
    "tanger",
    "tangiers",
    # CCAA / macro-regions as destinations
    "andalusia",
    "andalucia",
    "andalucía",
    "catalonia",
    "catalunya",
    "cataluna",
    "cataluña",
    "galicia",
    "euskadi",
    "basque country",
    "pais vasco",
    "país vasco",
    "navarra",
    "navarre",
    "aragon",
    "aragón",
    "extremadura",
    "cantabria",
    "asturias",
    "rioja",
    "la rioja",
    "castilla",
    "castile",
    "manchego",
    "la mancha",
    "castilla la mancha",
    "castilla-leon",
    "castilla y leon",
    "castilla y león",
    "valencian community",
    "comunidad valenciana",
    "murcia region",
    "region de murcia",
    "región de murcia",
    "baleares",
    "canarias",
    "canaries",
    # Islands archipelago names
    "balearics",
    # Attractions / brands
    "park guell",
    "guell",
    "gaudi",
    "gaudi",
    "prado museum",
    "reina sofia",
    "royal palace",
    "alcazar",
    "alcázar",
    "mezquita",
    "mezquita-catedral",
}

# Normalize token set once
TOKEN_EXCLUDE_N = {norm(t.strip()) for t in TOKEN_EXCLUDE if t.strip()}
PHRASE_EXCLUDE_N = sorted({norm(p) for p in PHRASE_EXCLUDE if p.strip()}, key=len, reverse=True)

# Costa X (generic coastal branding)
_COSTA_RE = re.compile(r"\bcosta\b", re.IGNORECASE)

_SPAIN_ANCHOR_RE = re.compile(
    r"\b(spain|spanish|espana|españa)\b",
    re.IGNORECASE | re.UNICODE,
)


def has_spain_anchor(text_norm_spaced: str) -> bool:
    # norm strips accents so españía -> espana
    if "spain" in text_norm_spaced or "spanish" in text_norm_spaced:
        return True
    if "espana" in text_norm_spaced:
        return True
    return bool(_SPAIN_ANCHOR_RE.search(text_norm_spaced))


def is_excluded(keyword: str) -> bool:
    raw = keyword.strip()
    if not raw:
        return True
    n = norm(raw)
    spaced = f" {n} "

    if not has_spain_anchor(spaced):
        return True

    for phrase in PHRASE_EXCLUDE_N:
        if phrase and f" {phrase} " in spaced:
            return True

    if _COSTA_RE.search(spaced):
        return True

    # Tokenize on non-letters (unicode)
    tokens = re.findall(r"[\w'-]+", n, flags=re.UNICODE)
    # Expand hyphen splits e.g. san-sebastian
    expanded: list[str] = []
    for t in tokens:
        expanded.append(t)
        if "-" in t:
            expanded.extend(t.split("-"))

    for t in expanded:
        if len(t) < 2:
            continue
        if t in TOKEN_EXCLUDE_N:
            return True

    return False


def read_text_smart(path: Path) -> str:
    raw = path.read_bytes()
    if raw.startswith(b"\xff\xfe"):
        return raw.decode("utf-16-le")
    if raw.startswith(b"\xfe\xff"):
        return raw.decode("utf-16-be")
    if raw.startswith(b"\xef\xbb\xbf"):
        return raw.decode("utf-8-sig")
    # UTF-16 without BOM but NUL bytes between ASCII (Planner exports)
    if len(raw) >= 2 and raw[1::2] == b"\x00" * (len(raw) // 2):
        return raw.decode("utf-16-le")
    return raw.decode("utf-8", errors="replace")


def main() -> int:
    inp = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(
        r"c:\Users\FEVER\Downloads\Keyword Stats 2026-05-07 at 13_02_21.csv"
    )
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else inp.with_name(
        inp.stem + "_spain-country-only" + inp.suffix
    )

    lines = read_text_smart(inp).splitlines()
    if len(lines) < 5:
        print("File too short", file=sys.stderr)
        return 1

    preamble = lines[:3]
    header_line = lines[3]
    data_lines = lines[4:]

    reader = csv.reader(data_lines, delimiter="\t")
    rows_out: list[list[str]] = []
    kept = dropped = 0
    for row in reader:
        if not row:
            continue
        kw = row[0].strip()
        if is_excluded(kw):
            dropped += 1
            continue
        rows_out.append(row)
        kept += 1

    with out.open("w", encoding="utf-8-sig", newline="") as f:
        for line in preamble:
            f.write(line + "\n")
        f.write(header_line + "\n")
        w = csv.writer(f, delimiter="\t", lineterminator="\n")
        w.writerows(rows_out)

    print(f"Written: {out}")
    print(f"Kept: {kept}, dropped: {dropped}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
